# Generated by Django 5.1.3 on 2024-11-09 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOffre', models.CharField(max_length=255)),
                ('program', models.FileField(error_messages={'invalid_extension': 'Le fichier doit être au format PDF, PNG, JPEG ou JPG.'}, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'])])),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=20, message='capacity must be under 20')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.FloatField()),
                ('id_offre', models.IntegerField()),
                ('coach_id', models.IntegerField()),
                ('nutrisionist_id', models.IntegerField()),
            ],
        ),
    ]
