# Generated by Django 5.1.3 on 2024-11-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOffres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='id_offre',
        ),
    ]
