# Generated by Django 5.1.3 on 2024-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('reference', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Référence produit')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description')),
                ('categorie', models.CharField(choices=[('sport', 'Sport'), ('nutrition', 'Nutrition')], max_length=20, verbose_name='Catégorie')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('quantite_disponible', models.PositiveIntegerField(verbose_name='Quantité disponible')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image')),
                ('marque', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marque')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimensions')),
                ('en_stock', models.BooleanField(default=True, verbose_name='En stock')),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Note moyenne')),
            ],
        ),
    ]
