# Generated by Django 5.1.3 on 2024-11-11 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='note_moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Poids (kg)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_disponible',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité disponible'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La référence doit contenir uniquement des lettres, chiffres et tirets.', regex='^[A-Za-z0-9-]+$')], verbose_name='Référence produit'),
        ),
    ]
