# Generated by Django 5.1.3 on 2024-11-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='program_fitness',
            field=models.FileField(blank=True, null=True, upload_to='fitness_programs/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='program_nutrition',
            field=models.FileField(blank=True, null=True, upload_to='nutrition_programs/'),
        ),
    ]
