# Generated by Django 5.1.3 on 2024-11-11 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_program_fitness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='goal_weight',
            field=models.FloatField(help_text='Desired weight in kilograms', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.FloatField(help_text='Height in centimeters', validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.TextField(default='https://e7.pngegg.com/pngimages/946/556/png-clipart-computer-icons-login-user-profile-client-smiley-%D0%B7%D0%BD%D0%B0%D1%87%D0%BA%D0%B8.png', help_text='URL of the profile picture', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.FloatField(help_text='Weight in kilograms', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AlterField(
            model_name='coachnutritionist',
            name='photo',
            field=models.TextField(default='https://www.shareicon.net/data/256x256/2016/07/21/799323_user_512x512.png', help_text='URL of the profile photo', validators=[django.core.validators.URLValidator()]),
        ),
    ]
