# Generated by Django 4.2 on 2024-11-07 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import theblog.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0004_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[theblog.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sport', 'sport'), ('nutrition', 'nutrition')], max_length=255, null=True),
        ),
    ]
