# Generated by Django 4.2 on 2024-11-07 11:04

from django.db import migrations, models
import theblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[theblog.models.validate_letters_only]),
        ),
    ]
